apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
type: Opaque
data:
  id_rsa: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkpRQUFBUUVBck5EOFZsNmx6dGd3SW9jak45bnFFdXZqU2tzMWl0ZjNiZ0duMlAyOWI4R25zcGJEZTVvVnVHcTdnL0tkTXI5aTlsYmRmYUlxMHdrcmxBYzd1OHc3ZWl2Y1BXeFNqaytQdlNCSnpNR2ErdmYvT3R6ZVVYdURWMTlGYjRZN2NLSUY4bUVwRmpvODltMlV2dFRVZ1FHY0hMdW9xd3JialNNb1NZcXJjcytlbHFNT1dqRDlEbzRCUXNQa0JhcFkzT3VrWUFaZWFCcGJNUERxZDRpUjQ2Q3dpUmw0TmIycjRqejJaM2lHMWVpU3BYVllac1kwaDFFek40aTlOdC9iVnVKWTQxL1ZUQU0xRnlxUGFhVHhHNHVINit6Q1RockxpWHhDTWRxa1BLWFFwY1pHdUFnTkM3RDIxajJIVFdRSVFHczRzZktZVEdnZ05ET0NFN1UzRExCSVN3PT0=
