apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
    - image: alpine:3.12.0
      name: app-1
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 5; echo 'hello!'; done;"]
      volumeMounts:
        - name: data-dir
          mountPath: /etc/a
    - image: alpine:3.12.0
      name: app-2
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 5; echo 'hello!'; done;"]
      volumeMounts:
        - name: data-dir
          mountPath: /etc/b
  restartPolicy: Never
  volumes:
    - name: data-dir
      emptyDir: {}
status: {}
